<?xml version="1.0"?>
<robot name="robot_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ratna_description)/urdf/robot_param.urdf.xacro" />
  <xacro:include filename="$(find ratna_description)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find ratna_description)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find ratna_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find ratna_description)/urdf/sensors/laser.urdf.xacro" />
  <xacro:include filename="$(find ratna_description)/urdf/sensors/camera.urdf.xacro" />
  <xacro:include filename="$(find ratna_description)/urdf/controllers/omni_drive.urdf.xacro" />

  <xacro:base
    length="${base_length}"
    width="${base_width * 2}"
    height="${base_height}"
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
  />

  <xacro:mecanum_wheel
    side="front_left"
    radius="${wheel_radius}"
    width="${wheel_width}"
    pos_x="${wheel_pos_x}"
    pos_y="${wheel_pos_y}"
    pos_z="${wheel_pos_z}"
    mass="${wheel_mass}"
    yaw="0.0"
  />

  <xacro:mecanum_wheel
    side="front_right"
    radius="${wheel_radius}"
    width="${wheel_width}"
    pos_x="${wheel_pos_x}"
    pos_y="${-wheel_pos_y}"
    pos_z="${wheel_pos_z}"
    mass="${wheel_mass}"
    yaw="0.0"
  />
  <xacro:mecanum_wheel
    side="rear_left"
    radius="${wheel_radius}"
    width="${wheel_width}"
    pos_x="${-wheel_pos_x}"
    pos_y="${wheel_pos_y}"
    pos_z="${wheel_pos_z}"
    mass="${wheel_mass}"
    yaw="0.0"
  />

  <xacro:mecanum_wheel
    side="rear_right"
    radius="${wheel_radius}"
    width="${wheel_width}"
    pos_x="${-wheel_pos_x}"
    pos_y="${-wheel_pos_y}"
    pos_z="${wheel_pos_z}"
    mass="${wheel_mass}"
    yaw="0.0"
  />

  <xacro:imu />

  <xacro:laser
    update_rate="10"
    ray_count="360"
    min_angle="3.14"
    max_angle="-3.14"
    min_range="0.08"
    max_range="25.0"
    frame_id="laser"
    topic_name="scan"
  >
    <xacro:insert_block name="laser_pose" />
  </xacro:laser>

  <xacro:depth_sensor>
    <xacro:insert_block name="depth_sensor_pose" />
  </xacro:depth_sensor>

  <xacro:omni_drive_controller />
</robot>