<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_height" value="0.1" />
    <xacro:property name="base_mass" value="10" />

    <xacro:property name="wheel_radius" value="0.07162" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="wheel_pos_x" value="${base_width/2}" />
    <xacro:property name="wheel_pos_y" value="${base_length/2 + wheel_width/2}" />
    <xacro:property name="wheel_pos_z" value="${-base_height/2}" />
    <xacro:property name="wheel_mass" value="0.6" />
    <xacro:property name="wheel_torque" value="20" />
    <xacro:property name="wheel_yaw" value="0.785398163" />


    <xacro:property name="laser_pose">
        <origin xyz="0.0 0.0 ${(base_height/2) + 0.035}" rpy="0 0 0" />
    </xacro:property>

    <xacro:property name="depth_sensor_pose">
        <origin xyz="${base_width} 0 ${base_height/2}" rpy="0 0 0" />
    </xacro:property>

</robot>